### ISSUE TITLE
Hard to see if KUVO URL is valid and being used

### ISSUE THREAD

**Issue by lord-carlos** [erikrichardlarson/unbox#17]
* I start the app
* select Rekordbox
* enter KUVO url
* Does it now get the data from KUVO or rekordbox DB?
* Do I just paste it in or do I have to unfocus the input field? (Klick somewhere else)

Maybe make it a separate service and not under rekordbox? Should not matter what software is pushing the song to KUVO.

**Comment by erikrichardlarson** [comment]
If you're on rb6 it will use both KUVO and the DB since KUVO doesn't log beatport tracks, and yeah you can just paste in the URL and it will work.

Yeah in the next release there will be a KUVO only mode, and going off your feature request I can make it so the most recent playlist we find is displayed so you know what playlist we're pulling. Thanks for the feedback!
