### ISSUE TITLE
Now Playing in Serato/Win 10 displays next (cued) track when loaded instead of track still playing

### ISSUE THREAD

**Issue by indigoisblue** [erikrichardlarson/unbox#22]
When a song is playing, Now Playing shows the right song, until I load a new song onto the other deck.  As soon as it is loaded there - not playing yet - Now Playing shows this new song instead of the song that is still playing.

Win 10/Serato

PS the instructions on the main page aren't for Win and are a little confusing; the localhost links you give there don't seem to be valid filenames for windows, and there aren't multiple steps in Win/Serato setup. :)

**Comment by indigoisblue** [comment]
Am I missing something obvious here to not get a response?  Apologies if so but would love a pointer or anything...

**Comment by erikrichardlarson** [comment]
Yo sorry I missed this! 

This is a known issue with Serato, the history updates immediately. Some get around this by adding in a delay of say 30s before the new track is reported out. Also my bad on the instructions, with the new release you should just be able to download the app and follow the steps in the app to the end where you copy the url for your browser source. Again sorry for the late response!

**Comment by indigoisblue** [comment]
Ah hm, that's a bummer.. a delay isn't a great solution because some tracks are much longer than others.  Thanks for the reply!

**Comment by Nass86** [comment]
A workaround in OBS could be to duplicate your scene(s) and have one version without writing and another with writing. 

I have scenes

1 FACE
2 DECKS
3 FACE FREEZE
4 DECKS FREEZE

I make hot keys numbers 1 2 3 and 4 for each scene. OBS Advanced scene switcher switches between scenes 1 and 2 every 20 seconds. If I need to be on the screen for longer I press 3 which has no rules (it will stay there) and if I need to go off the screen I press scene 4 so I have longer to pour a drink, go to the toilet etc. When I return I press 1.

I'm contemplating adding a 5 TRACK ID screen that is a copy of one of these screens, and then I can control when it is on/off. When I used to watch music programs as a kid (MTV?) I could swear it would nod the track details at the start and end but otherwise play a video so I think that's where i'm getting my thought process from.

**Comment by Nass86** [comment]
See example.

**Comment by erikrichardlarson** [comment]
@indigoisblue There is a new serato live mode that will follow master / grab your latest public tracklists which should solve the issue here
