### ISSUE TITLE
Multiple tracks playing on rekordbox

### ISSUE THREAD

**Issue by thegamecat** [erikrichardlarson/unbox#3]
If multiple tracks are playing at the same time in Rekordbox it seems only one shows in Now playing, is there an obvious way to resolve this?

**Comment by thegamecat** [comment]
I looked at the code and it seems straight forward enough for me to read but I can't seem to open the sqlite dB to look at the behaviour to see if I can do something with it to add the multiple tracks.

I'm using sqlite dB browser how are you getting the master dB to open?

**Comment by erikrichardlarson** [comment]
There's not really an obvious way since rekordbox only logs the start time of the track, and you'd need an end time logged to reliably log two tracks to the now playing overlay. Both could come up in the play history overlay though if each track was logged to the now playing overlay. 

So you need to decrypt the database, you can find the key to do so if you dig around a bit. I don't really want to post that here as I don't think Pioneer would like that.

**Comment by thegamecat** [comment]
Ok so the logic is when a next track is logged the previous one goes into history? 

I've found the dp but I don't seem to be able to use that in sqlite db browser cypher. Appreciate your statement :)

**Comment by erikrichardlarson** [comment]
Yeah exactly, once a new track is seen, the current "Now Playing" tracks moves to the top of the "Previous" section.

**Comment by thegamecat** [comment]
I still can't get into the stupid db to take a look...

Tested it in anger tonight on a live stream, was pretty good, only issue was when I played 2 mixes of the same song at the same time (ish). It showed just the one track. I'm guessing this is a beatport link data issue. 

Really want to get into the code but need that db access.

**Comment by erikrichardlarson** [comment]
I don't think Beatport link data isn't the issue here. This happens because rekordbox writes to the history every minute, and we poll the db every 10 seconds. So if the tracks were played within 10 seconds of each other, we only catch the most recently logged track. 

What overlay are you using? By pulling down the two most recently played tracks, we could still write tracks played within the db polling period to the play history overlay.

**Comment by thegamecat** [comment]
Ah interesting. I might have 3 tracks playing at the same time for 3 minutes. 

Streaming through OBS / Stream Elements.

**Comment by erikrichardlarson** [comment]
Ah in that case I can grab the three most recently played tracks and they'd get logged to the play history overlay. Ideally I could see that the tracks are playing before the minute mark, but tbd if I can find a way to do this.

**Comment by frank01wong** [comment]
hey erik, good job on the app. I've been using lepopal's version and yours has the upper hagnd because of the ability to bring the previous track as well.

Question for you 
1- is it possible to get the output as a .txt rather than an html premade format?
2- for the comment about the 10s fetch, you can check popal's code, he allows the user to select the frequency at which the data is fetched. I set mine to 60-120s depending on how fast i mix.

Once again, great job.
frank

**Comment by erikrichardlarson** [comment]
Thanks! 

1) For sure, so you just want the history as a txt file?
2) Yeah I'm planning to add this feature, particularly for Serato users not using the live playlist feature because Serato writes to the history immediately. I assume you're on rb6? since rb6 doesn't write to history until 60s after a track has played out, you should be at ~70s before a track is logged to the history, is this what you're looking for?

**Comment by frank01wong** [comment]
1- yes, just so that I can have an alternative option to post the last X songs. I'm not sure how many you could fetch in a .txt from the history bank
2- Yes i'm RB6. It's roughly 45-60s (and kuvo about 30 it's faster) but that also means if you cue a loop early on, it'll change the current track right away! I usually use 120s because i know on average i start to cue 2 minutes before so it's just so that people with different mixing workflows can adapt it to their needs.

Cheers!

**Comment by thegamecat** [comment]
Is there any way to get the exact tracks that are actually playing rb?

**Comment by erikrichardlarson** [comment]
@thegamecat Yeah I'm planning to incorporate this [work](https://github.com/Unreal-Dan/RekordBoxSongExporter) so you'd get real-time updates out of rekordbox on Windows 64-bit. Are you on Windows 64-bit?

**Comment by frank01wong** [comment]
@erikrichardlarson if you pull off real time deck play... you are a genius. I was told it wasn't possible in rekordbox if you manage.... omg!!!!!!!!!!

**Comment by frank01wong** [comment]
> @thegamecat Yeah I'm planning to incorporate this [work](https://github.com/Unreal-Dan/RekordBoxSongExporter) so you'd get real-time updates out of rekordbox on Windows 64-bit. Are you on Windows 64-bit?

I checked it out, i'm just a bit nervous trying it out. the whole project is only 23kb, doesn't it seem small? Don't want to risk it before someone can vet the code, I'm not a dev.

**Comment by erikrichardlarson** [comment]
@frank01wong It's small because it hooks directly into rekordbox and injects some code that will output the track data in real-time. I've been working with the author directly and can confirm that the author has put in a lot of work to make this work as intended, and knows his stuff. I've tested the code as well and it works as intended, I'll be adding two new modes to unbox that use this work very soon.

**Comment by frank01wong** [comment]
ok fantastic ill be giving it a try, thanks a lot for the reply erik!

**Comment by frank01wong** [comment]
it is amazing indeed!

**Comment by fivefortyfour** [comment]
i can't get that windows hook to work? How does it launch rekordbox? There's no exe file in the download?

**Comment by erikrichardlarson** [comment]
@fivefortyfour i've integrated unreal dan's work with the latest release, hope y'all like it!
