### ISSUE TITLE
High CPU spikes when using KUVO mode

### ISSUE THREAD

**Issue by lord-carlos** [erikrichardlarson/unbox#46]
Hi

Unbox 8.1
When using KUVO mode, every ~10 seconds unbox spikes on **all** threads.
This does not happen in DB mode. There you just have a small spike on a single thread.
![image](https://user-images.githubusercontent.com/155855/120341765-73c60500-c2f7-11eb-8c3d-c7a7aaa3fdd1.png)

I know it's just short and not much compared to OBS / Rekordbox itself. But it should just be a simple http get?
There might be space for improvements :)

Sometimes, when you go from KUVO to DB without closing, it seems to continue? Might still pull data even though we switched mode?

With kind regards.

**Comment by erikrichardlarson** [comment]
Yeah this is caused by puppeteer launching a new browser instance, puppeteer also significantly contributes to the size of unbox. I'll be migrating to Microsoft's Playwright and using their browser context to prevent these spikes going forward, and decrease the size of the unbox app / speed up install time: https://playwright.dev/docs/core-concepts#browser-contexts

Also we still need to use a browser and can't do a simple http get since KUVO uses JS rendered pages. 

Thanks for help and feedback here!
