### ISSUE TITLE
Add link to manage paid subscription to README

### ISSUE THREAD

**Issue by voxxit** [erikrichardlarson/unbox#85]
There doesn't seem to be an option to manage my subscription with Stripe anywhere that I can find. It would be very helpful for people who pay a monthly subscription fee to be able to go in and cancel it without having to send you an email and wait for a response.

Could you add something like this? I need to cancel the sub, unfortunately. 

Thanks!

**Comment by erikrichardlarson** [comment]
Hey apologies for the issue here, you can find a Cancel button in the bottom right of Step 4 in the unbox setup. Here's a screenshot of what that looks like, just let me know if you don't see this in your app post-login:

<img width="839" alt="Screen Shot 2022-05-18 at 9 00 53 AM" src="https://user-images.githubusercontent.com/17460309/169088830-a97ded23-b218-4e5b-8aa5-50c37fa17b44.png">
